language: ruby
sudo: false
cache: bundler
script:
- bundle exec rake spec
rvm:
- 2.3
env:
- FACTER_GEM_VERSION="~> 1.6.0"
- FACTER_GEM_VERSION="~> 1.7.0"
- FACTER_GEM_VERSION="~> 2.0.0"
- FACTER_GEM_VERSION="~> 2.1.0"
- FACTER_GEM_VERSION="~> 2.2.0"
- FACTER_GEM_VERSION="~> 2.3.0"
- FACTER_GEM_VERSION="~> 2.4.0"
- FACTER_GEM_VERSION="~> 2.0" COVERAGE=yes
matrix:
  fast_finish: true
notifications:
  email: false
deploy:
  provider: rubygems
  api_key:
    secure: Ja5JTWVsXcpYKVBrM35h9jLBoEuSm2f28A7UBk/culOC45dXzlS1BQfcxuVuNeRZ1/pPHHOnCM11yfliqJ2eF6FsNTqaLiFnNDAP/qPI2an9T1FO9dnBQ/EJp3jMp6DcXvb7CbYMS9n61CM+W0RzAdGpRK6AGLFAN5Ttba1SEIGPtlBV6e0MOu7Ma9DI7tFboqi3quSTPhvXUHpyYXDicQ+2/eijAWde/Tll3wJB8ir9lqmNh/xV9qHKdjZsAK8PG6PiuuaVsBUiQMFnapZD2OZmgLJFrOLnTvvntdcsQecsvlykHZXgbqta372KxDRIsJ2ld9a2GiL/wZDvZ9SWC+r5RAKxkvtKyQPezecO9yjJxaYAryY06YA92WibmZPBuODI4iz0MkueiulXjT4W5e/04Dj+oHtNTSGOucM5J8a08NN0UNW0IpJL/VDIw7viyXc2DzwrPJGzn/jfjzvjX7ITNKS2DIPNps/thmiGu88+Snx/5O3Cmg15OgrIlSQfkJmnLedR+qQHoE5Xk4laIJ/+4L3o9X5lFwzQYneY4u/xedKrZl66idlMGqxkbmzyf4gjKzq7pZPnFePavJwrJlCU7HXangYcOotBo4Lb2lwpeL2ilgrgLn1p7bfLdTlQcNCH4WyRAyOlVtN4vNPVc7+a3n+BL0gz7Y1B7NQUukQ=
  gem: facterdb
  on:
    tags: true
    repo: camptocamp/facterdb
